# version_base: null

# seed: 42
# device_id: 0

# datasets:
#   dataset_root: './data'
#   dataset_name: 'mutag'
#   random_split_flag: true
#   data_split_ratio: [0.8, 0.1, 0.1]

# models:
#   gnn_name: 'gcn'
#   gnn_saving_dir: ./checkpoints/42
#   param:
#     graph_classification: true
#     batch_size: 128
#     num_epochs: 300
#     num_early_stop: 50
#     learning_rate: 0.001
#     weight_decay: 0.0001
#     gnn_latent_dim: [128, 128, 128]
#     fc_latent_dim: [128]
#     gnn_dropout: 0.0
#     fc_dropout: 0.0
#     milestones: [150, 250]
#     gamma: 0.5

version_base: null

seed: 42
device_id: 0   # Use -1 for CPU

datasets:
  dataset_root: './data'
  dataset_name: 'mutag'
  random_split_flag: true
  data_split_ratio: [0.8, 0.1, 0.1]

models:
  gnn_name: 'gcn'
  gnn_saving_dir: ./checkpoints/42
  param:
    mutag:
      graph_classification: true
      batch_size: 128
      num_epochs: 300
      num_early_stop: 50
      learning_rate: 0.001
      weight_decay: 0.0001
      gnn_latent_dim: [128, 128, 128]
      fc_latent_dim: [128]
      gnn_dropout: 0.0
      fc_dropout: 0.0
      milestones: [150, 250]
      gamma: 0.5
